language: php

before_install:
- composer require phpunit/phpunit:~7.0 satooshi/php-coveralls:~2.0
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v